name: Sync Issues Status
description: Moves issues to a specified status column

inputs:
  project-token:
    description: 'GitHub token with project permissions'
    required: true
  project-number:
    description: 'GitHub Project number'
    required: true
  issues:
    description: 'JSON array of issue numbers to move (optional, falls back to parsing commits)'
    required: false
    default: ''
  to-status:
    description: 'Target status column'
    required: true

runs:
  using: composite
  steps:
    - name: Move issues to ${{ inputs.to-status }} 📋
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.project-token }}
        script: |
          const toStatus = '${{ inputs.to-status }}';
          const projectNumber = parseInt('${{ inputs.project-number }}');
          const issuesInput = '${{ inputs.issues }}';
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // Get issue numbers: from input or parse commits
          let issueNumbers;
          if (issuesInput && issuesInput !== '[]') {
            issueNumbers = JSON.parse(issuesInput);
            console.log(`Using provided issues: ${issueNumbers.join(', ')}`);
          } else {
            // Fallback: parse commits
            const commits = context.payload.commits || [];
            const pattern = /(?:fix|fixes|fixed|close|closes|closed|resolve|resolves|resolved)\s*#(\d+)/gi;
            const parsed = new Set();
            for (const commit of commits) {
              let match;
              while ((match = pattern.exec(commit.message)) !== null) {
                parsed.add(parseInt(match[1]));
              }
            }
            issueNumbers = [...parsed];
            console.log(`Parsed from commits: ${issueNumbers.join(', ') || 'none'}`);
          }

          if (issueNumbers.length === 0) {
            console.log('No issues to move');
            return;
          }

          // Get the project
          const projectQuery = `
            query($owner: String!, $number: Int!) {
              user(login: $owner) {
                projectV2(number: $number) {
                  id
                  field(name: "Status") {
                    ... on ProjectV2SingleSelectField {
                      id
                      options { id name }
                    }
                  }
                }
              }
            }
          `;

          const projectData = await github.graphql(projectQuery, { owner, number: projectNumber });
          const project = projectData.user.projectV2;
          const statusField = project.field;
          const targetOption = statusField.options.find(o => o.name === toStatus);

          if (!targetOption) {
            console.log(`Could not find "${toStatus}" status option`);
            return;
          }

          // Move each issue
          for (const issueNumber of issueNumbers) {
            try {
              // Get the issue's project item ID
              const issueQuery = `
                query($owner: String!, $repo: String!, $number: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $number) {
                      id
                      projectItems(first: 10) {
                        nodes {
                          id
                          project { id }
                        }
                      }
                    }
                  }
                }
              `;

              const issueData = await github.graphql(issueQuery, {
                owner,
                repo,
                number: issueNumber
              });

              const projectItem = issueData.repository.issue.projectItems.nodes
                .find(item => item.project.id === project.id);

              if (!projectItem) {
                console.log(`Issue #${issueNumber} is not in the project`);
                continue;
              }

              // Update the status
              const mutation = `
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: { singleSelectOptionId: $optionId }
                  }) {
                    projectV2Item { id }
                  }
                }
              `;

              await github.graphql(mutation, {
                projectId: project.id,
                itemId: projectItem.id,
                fieldId: statusField.id,
                optionId: targetOption.id
              });

              console.log(`Moved issue #${issueNumber} to ${toStatus}`);
            } catch (error) {
              console.log(`Failed to move issue #${issueNumber}: ${error.message}`);
            }
          }
