name: Move Issues to Project Status
description: Moves issues referenced in commit messages to a specified project status

inputs:
  status-name:
    description: 'Target status name (e.g., "Deployed in Staging", "Deployed in Production")'
    required: true
  project-token:
    description: 'GitHub token with project permissions'
    required: true
  project-number:
    description: 'GitHub Project number'
    required: true

runs:
  using: composite
  steps:
    - name: Move issues to ${{ inputs.status-name }} 📋
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.project-token }}
        script: |
          const statusName = '${{ inputs.status-name }}';
          const projectNumber = parseInt('${{ inputs.project-number }}');
          const owner = context.repo.owner;

          // Get commits from the push
          const commits = context.payload.commits || [];
          const issueNumbers = new Set();

          // Extract issue numbers from commit messages (fix #123, close #123, etc.)
          const pattern = /(?:fix|fixes|fixed|close|closes|closed|resolve|resolves|resolved)\s*#(\d+)/gi;
          for (const commit of commits) {
            let match;
            while ((match = pattern.exec(commit.message)) !== null) {
              issueNumbers.add(parseInt(match[1]));
            }
          }

          if (issueNumbers.size === 0) {
            console.log('No issues to move');
            return;
          }

          console.log(`Found issues to move: ${[...issueNumbers].join(', ')}`);

          // Get the project
          const projectQuery = `
            query($owner: String!, $number: Int!) {
              user(login: $owner) {
                projectV2(number: $number) {
                  id
                  field(name: "Status") {
                    ... on ProjectV2SingleSelectField {
                      id
                      options { id name }
                    }
                  }
                }
              }
            }
          `;

          const projectData = await github.graphql(projectQuery, { owner, number: projectNumber });
          const project = projectData.user.projectV2;
          const statusField = project.field;
          const targetOption = statusField.options.find(o => o.name === statusName);

          if (!targetOption) {
            console.log(`Could not find "${statusName}" status option`);
            return;
          }

          // Move each issue
          for (const issueNumber of issueNumbers) {
            try {
              // Get the issue's project item ID
              const issueQuery = `
                query($owner: String!, $repo: String!, $number: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $number) {
                      id
                      projectItems(first: 10) {
                        nodes {
                          id
                          project { id }
                        }
                      }
                    }
                  }
                }
              `;

              const issueData = await github.graphql(issueQuery, {
                owner,
                repo: context.repo.repo,
                number: issueNumber
              });

              const projectItem = issueData.repository.issue.projectItems.nodes
                .find(item => item.project.id === project.id);

              if (!projectItem) {
                console.log(`Issue #${issueNumber} is not in the project`);
                continue;
              }

              // Update the status
              const mutation = `
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: { singleSelectOptionId: $optionId }
                  }) {
                    projectV2Item { id }
                  }
                }
              `;

              await github.graphql(mutation, {
                projectId: project.id,
                itemId: projectItem.id,
                fieldId: statusField.id,
                optionId: targetOption.id
              });

              console.log(`Moved issue #${issueNumber} to ${statusName}`);
            } catch (error) {
              console.log(`Failed to move issue #${issueNumber}: ${error.message}`);
            }
          }
